title: "Satwik Chivukula"
description: "Data Analyst | Aspiring Data Scientist"
theme: jekyll-theme-cayman

# Navigation
navbar-links:
  Home: "/"
  Projects: "/projects"
  Blog: "/blog"
  About: "/about"
