title: "Chivukula Sairam Satwik"
email: saisatwik4132@gmail.com
description: >- # this means to wrap text
  This is my professional portfolio.
baseurl: "" # leave blank for user site
url: "https://sai4132.github.io" # replace YOUR_USERNAME
theme: jekyll-theme-cayman    # GitHub Pages default compatible theme
plugins: []
